#!/bin/sh
# genbib.sh --- auto-generated by urithesis.cls
# Run this script from the directory containing your .tex files
# to produce a fully resolved PDF.

set -e

echo "==> Pass 1: pdflatex (collecting citations)..."
pdflatex thesis

echo "==> Running BibTeX on each aux file..."
 bibtex chapter1
 bibtex chapter2
 bibtex chapter3

echo "==> Pass 2: pdflatex (reading .bbl files)..."
pdflatex thesis

echo "==> Pass 3: pdflatex (resolving cross-references)..."
pdflatex thesis

echo "==> Done. Output: thesis.pdf"
